#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/generated/network.env"
COMPOSE_FILE="${ROOT_DIR}/compose.yaml"

[[ -f "${ENV_FILE}" ]] || { echo "Missing ${ENV_FILE}; run setup-network.sh first." >&2; exit 1; }
# shellcheck disable=SC1090
source "${ENV_FILE}"
NETWORK_NAME="${NETWORK_NAME:-elements-localnet}"
VOLUME_NAMESPACE="${VOLUME_NAMESPACE:-${NETWORK_NAME}}"
# First host port publishing a node's P2P listener so peers outside Docker can join.
# Node i is published at base+i-1.
P2P_HOST_PORT_BASE="${P2P_HOST_PORT_BASE:-}"
# localhost publishes on 127.0.0.1 only, lan publishes on every host interface,
# disabled publishes no P2P port at all. Public RPC is never published.
P2P_EXPOSURE="${P2P_EXPOSURE:-localhost}"
EXPLORER_IMAGE_TAG="${EXPLORER_IMAGE_TAG:-phase2a}"
DASHBOARD_HOST_PORT="${DASHBOARD_HOST_PORT:-8080}"

case "${P2P_EXPOSURE}" in
  localhost) p2p_bind_address="127.0.0.1" ;;
  lan)       p2p_bind_address="0.0.0.0" ;;
  disabled)  p2p_bind_address="" ;;
  *) echo "P2P_EXPOSURE must be localhost, lan, or disabled." >&2; exit 2 ;;
esac
[[ -n "${P2P_HOST_PORT_BASE}" ]] || p2p_bind_address=""

explorer_primary="node-01"
((NODE_COUNT >= 2)) && explorer_primary="node-02"

tmp_file="${COMPOSE_FILE}.tmp"
cleanup() { rm -f "${tmp_file}"; }
trap cleanup EXIT

cat >"${tmp_file}" <<EOF
# Generated by scripts/generate-compose.sh. Re-run setup-network.sh to change topology.
name: ${NETWORK_NAME}

x-node-common: &node-common
  image: ${NETWORK_NAME}-node:${ELEMENTS_VERSION}
  restart: unless-stopped
  read_only: true
  tmpfs:
    - /tmp:size=16m,mode=1777
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL
  networks:
    - localnet
  healthcheck:
    test: ["CMD", "/usr/local/bin/node-healthcheck"]
    interval: 5s
    timeout: 6s
    retries: 30
    start_period: 10s

services:
EOF

for ((i = 1; i <= NODE_COUNT; i++)); do
  node="$(printf 'node-%02d' "${i}")"
  host_port=$((RPC_HOST_PORT_BASE + i - 1))
  ip_octet=$((10 + i))
  {
    printf '  %s:\n' "${node}"
    printf '    <<: *node-common\n'
    if ((i == 1)); then
      printf '    build:\n      context: .\n      dockerfile: Dockerfile\n      args:\n        LOCAL_UID: "%s"\n        LOCAL_GID: "%s"\n' "${LOCAL_UID}" "${LOCAL_GID}"
    fi
    printf '    container_name: %s-%s\n' "${NETWORK_NAME}" "${node}"
    printf '    hostname: %s\n' "${node}"
    printf '    command: ["-datadir=/data", "-conf=/config/elements.conf", "-printtoconsole=1"]\n'
    printf '    volumes:\n'
    printf '      - %s-data:/data\n' "${node}"
    printf '      - ./generated/nodes/%s/elements.conf:/config/elements.conf:ro\n' "${node}"
    printf '    ports:\n'
    printf '      - "127.0.0.1:%d:7040"\n' "${host_port}"
    if [[ -n "${p2p_bind_address}" ]]; then
      printf '      - "%s:%d:7042"\n' "${p2p_bind_address}" "$((P2P_HOST_PORT_BASE + i - 1))"
    fi
    printf '    networks:\n      localnet:\n        ipv4_address: 172.28.239.%d\n' "${ip_octet}"
    if ((i > 1)); then
      printf '    depends_on:\n      node-01:\n        condition: service_healthy\n'
    fi
  } >>"${tmp_file}"
done

cat >>"${tmp_file}" <<EOF
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
      args:
        LOCAL_UID: "${LOCAL_UID}"
        LOCAL_GID: "${LOCAL_GID}"
    image: ${NETWORK_NAME}-producer:${ELEMENTS_VERSION}
    container_name: ${NETWORK_NAME}-producer
    profiles: ["producer"]
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=8m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      RPC_URL: http://node-01:7040
      RPC_CREDENTIALS_FILE: /run/localnet/node-01.rpc
      PAYOUT_ADDRESS_FILE: /run/localnet/payout-address
      BLOCK_INTERVAL: "${BLOCK_INTERVAL}"
      PRODUCER_MODE: automatic
    volumes:
      - producer-lock:/producer-lock
      - producer-status:/producer-status
      - ./generated/secrets/node-01.rpc:/run/localnet/node-01.rpc:ro
      - ./generated/public/payout-address:/run/localnet/payout-address:ro
    networks:
      - localnet
    depends_on:
      node-01:
        condition: service_healthy

  explorer:
    build:
      context: ./explorer
      dockerfile: Dockerfile
      args:
        LOCAL_UID: "${LOCAL_UID}"
        LOCAL_GID: "${LOCAL_GID}"
    image: ${NETWORK_NAME}-explorer:${EXPLORER_IMAGE_TAG}
    container_name: ${NETWORK_NAME}-explorer
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=64m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      INVENTORY_FILE: /run/localnet/inventory.json
      ASSET_REGISTRY_FILE: /run/localnet/assets.json
      EXPLORER_DB_PATH: /var/lib/elements-explorer/explorer.db
      EXPLORER_SECRETS_DIR: /run/explorer-secrets
      EXPLORER_PRIMARY_NODE: ${explorer_primary}
    volumes:
      - ./generated/inventory.json:/run/localnet/inventory.json:ro
      - ./generated/public/assets.json:/run/localnet/assets.json:ro
      - ./generated/secrets/monitor:/run/monitor-secrets:ro
      - ./generated/secrets/explorer:/run/explorer-secrets:ro
      - producer-status:/run/producer-status:ro
      - explorer-db:/var/lib/elements-explorer
    ports:
      - "127.0.0.1:${DASHBOARD_HOST_PORT}:8080"
    networks:
      - localnet
    depends_on:
      node-01:
        condition: service_started
    healthcheck:
      test: ["CMD", "/usr/local/bin/explorer", "-healthcheck"]
      interval: 10s
      timeout: 4s
      retries: 20
      start_period: 10s

networks:
  localnet:
    name: ${NETWORK_NAME}-bridge
    driver: bridge
    ipam:
      config:
        - subnet: ${LOCALNET_SUBNET}

volumes:
EOF

for ((i = 1; i <= NODE_COUNT; i++)); do
  node="$(printf 'node-%02d' "${i}")"
  printf '  %s-data:\n    external: true\n    name: %s-%s-data\n' "${node}" "${VOLUME_NAMESPACE}" "${node}" >>"${tmp_file}"
done
cat >>"${tmp_file}" <<EOF
  producer-lock:
    external: true
    name: ${VOLUME_NAMESPACE}-producer-lock
  producer-status:
    external: true
    name: ${VOLUME_NAMESPACE}-producer-status
  explorer-db:
    external: true
    name: ${VOLUME_NAMESPACE}-explorer-db
EOF

mv "${tmp_file}" "${COMPOSE_FILE}"
trap - EXIT
echo "Generated ${COMPOSE_FILE} for ${NODE_COUNT} node(s); P2P exposure: ${P2P_EXPOSURE}."
