#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/generated/network.env"
COMPOSE_FILE="${ROOT_DIR}/compose.yaml"

[[ -f "${ENV_FILE}" ]] || { echo "Missing ${ENV_FILE}; run setup-network.sh first." >&2; exit 1; }
# shellcheck disable=SC1090
source "${ENV_FILE}"
VOLUME_NAMESPACE="${VOLUME_NAMESPACE:-elements-localnet}"
# First host port publishing a node's P2P listener so peers outside Docker can join.
# Node i is published at base+i-1. Empty disables external P2P entirely.
P2P_HOST_PORT_BASE="${P2P_HOST_PORT_BASE:-}"

tmp_file="${COMPOSE_FILE}.tmp"
cleanup() { rm -f "${tmp_file}"; }
trap cleanup EXIT

cat >"${tmp_file}" <<EOF
# Generated by scripts/generate-compose.sh. Re-run setup-network.sh to change topology.
name: elements-localnet

x-node-common: &node-common
  image: elements-localnet-node:${ELEMENTS_VERSION}
  restart: unless-stopped
  read_only: true
  tmpfs:
    - /tmp:size=16m,mode=1777
  security_opt:
    - no-new-privileges:true
  cap_drop:
    - ALL
  networks:
    - localnet
  healthcheck:
    test: ["CMD", "/usr/local/bin/node-healthcheck"]
    interval: 5s
    timeout: 6s
    retries: 30
    start_period: 10s

services:
EOF

for ((i = 1; i <= NODE_COUNT; i++)); do
  node="$(printf 'node-%02d' "${i}")"
  host_port=$((RPC_HOST_PORT_BASE + i - 1))
  ip_octet=$((10 + i))
  {
    printf '  %s:\n' "${node}"
    printf '    <<: *node-common\n'
    if ((i == 1)); then
      printf '    build:\n      context: .\n      dockerfile: Dockerfile\n      args:\n        LOCAL_UID: "%s"\n        LOCAL_GID: "%s"\n' "${LOCAL_UID}" "${LOCAL_GID}"
    fi
    printf '    container_name: elements-localnet-%s\n' "${node}"
    printf '    hostname: %s\n' "${node}"
    printf '    command: ["-datadir=/data", "-conf=/config/elements.conf", "-printtoconsole=1"]\n'
    printf '    volumes:\n'
    printf '      - %s-data:/data\n' "${node}"
    printf '      - ./generated/nodes/%s/elements.conf:/config/elements.conf:ro\n' "${node}"
    printf '    ports:\n'
    printf '      - "127.0.0.1:%d:7040"\n' "${host_port}"
    if [[ -n "${P2P_HOST_PORT_BASE}" ]]; then
      printf '      - "0.0.0.0:%d:7042"\n' "$((P2P_HOST_PORT_BASE + i - 1))"
    fi
    printf '    networks:\n      localnet:\n        ipv4_address: 172.28.239.%d\n' "${ip_octet}"
    if ((i > 1)); then
      printf '    depends_on:\n      node-01:\n        condition: service_healthy\n'
    fi
  } >>"${tmp_file}"
done

cat >>"${tmp_file}" <<EOF
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
      args:
        LOCAL_UID: "${LOCAL_UID}"
        LOCAL_GID: "${LOCAL_GID}"
    image: elements-localnet-producer:${ELEMENTS_VERSION}
    container_name: elements-localnet-producer
    profiles: ["producer"]
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=8m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      RPC_URL: http://node-01:7040
      RPC_CREDENTIALS_FILE: /run/localnet/node-01.rpc
      PAYOUT_ADDRESS_FILE: /run/localnet/payout-address
      BLOCK_INTERVAL: "${BLOCK_INTERVAL}"
      PRODUCER_MODE: automatic
    volumes:
      - producer-lock:/producer-lock
      - producer-status:/producer-status
      - ./generated/secrets/node-01.rpc:/run/localnet/node-01.rpc:ro
      - ./generated/public/payout-address:/run/localnet/payout-address:ro
    networks:
      - localnet
    depends_on:
      node-01:
        condition: service_healthy

  network-status:
    build:
      context: ./network-status
      dockerfile: Dockerfile
      args:
        LOCAL_UID: "${LOCAL_UID}"
        LOCAL_GID: "${LOCAL_GID}"
    image: elements-localnet-network-status:phase1
    container_name: elements-localnet-network-status
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:size=8m,mode=1777
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    environment:
      INVENTORY_FILE: /run/localnet/inventory.json
    volumes:
      - ./generated/inventory.json:/run/localnet/inventory.json:ro
      - ./generated/secrets/monitor:/run/monitor-secrets:ro
      - producer-status:/run/producer-status:ro
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - localnet
    depends_on:
      node-01:
        condition: service_started
    healthcheck:
      test: ["CMD", "/usr/local/bin/network-status", "-healthcheck"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s

networks:
  localnet:
    name: elements-localnet-bridge
    driver: bridge
    ipam:
      config:
        - subnet: ${LOCALNET_SUBNET}

volumes:
EOF

for ((i = 1; i <= NODE_COUNT; i++)); do
  node="$(printf 'node-%02d' "${i}")"
  printf '  %s-data:\n    external: true\n    name: %s-%s-data\n' "${node}" "${VOLUME_NAMESPACE}" "${node}" >>"${tmp_file}"
done
cat >>"${tmp_file}" <<EOF
  producer-lock:
    external: true
    name: ${VOLUME_NAMESPACE}-producer-lock
  producer-status:
    external: true
    name: ${VOLUME_NAMESPACE}-producer-status
EOF

mv "${tmp_file}" "${COMPOSE_FILE}"
trap - EXIT
echo "Generated ${COMPOSE_FILE} for ${NODE_COUNT} node(s)."
